# Generated by Django 5.0.8 on 2024-08-28 10:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='images/')),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=255, unique=True)),
                ('ProductDescription', models.CharField(max_length=255)),
                ('ProductUnitPrice', models.FloatField()),
                ('ProductStatus', models.CharField(max_length=20)),
                ('InitialLoadStock', models.IntegerField()),
                ('StockLeft', models.IntegerField()),
                ('ProductCategory', models.CharField(max_length=50)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifiedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=150, unique=True)),
                ('EmailId', models.EmailField(max_length=254, unique=True)),
                ('MobileNo', models.CharField(max_length=15)),
                ('Age', models.PositiveIntegerField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Other')], max_length=10)),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ModifiedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.CharField(max_length=50)),
                ('Timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('AccessToken', models.CharField(max_length=255)),
                ('RefreshToken', models.CharField(max_length=255)),
                ('UserId', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPurchased',
            fields=[
                ('PurchaseOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('PurchasedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.product')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
