# Generated by Django 5.0.6 on 2024-08-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='UserModel.user'),
        ),
    ]
